# From: https://github.com/jeremyhuiskamp/golang-docker-scratch/blob/026ddd6232ecf1f28974f404d6b8247b9d2cf4df/.github/workflows/build.yml
name: build

on:
  push:
  pull_request:
  schedule:
    # because we're dependent on some docker images that can change
    - cron: '0 0 1 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build & run the docker image
      run: |
        make run
